[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.93", features = ["backtrace"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
